void errores(){
    int hola = 45 
    hola = 45;
    
    hola = 45 //conseguir que vaya hasta el ;
    hola = 45;
    int a = 5;
    hola 45;
    hola = 43;
    
     if (3=2){
      hola = 3
    }

    if (a==b { 
        int hola;
    }

    if (a==b) { 
        int;
    }
    
    for (int i=0 ;i<3;i = i+1){
        int a = 0;
    }

    for (int i=0 ;i<3;i = i+1){
        int a = 0
    }
    
    for (int i=0 i<3;i = i+1){
        int a = 0;
    }

    while(true {
        a = b;
    }

    while(true){
        a = b;
    }

    while(true){
        print ("hola")
    }

    switch(valor){
        case 3: a = 3; break;
        case 4: a = 4; break;
        default: a = 5;
    }

    switch(valor{
        case 3: a = 3; break;
        case 4: a = 4; break;
        default: a = 5; 
    }

    switch(valor){
        case : a = 3; break;
        case 4: a = 4; break; //error instruccion
        default: a = 5; 
    }

    switch(valor{
        case 3: a = 3;;
        case 4: a = ; break;
        default: a = 5; 
    }
}

void main(){
        switch(valor){
        case 5: a = 3; break;
        case 4: a = 4; break;
        default: a = 5    //cuando es la ultima instruccion, no entra en el caso del switch
                 int a = 4;
    }

    int a = 2; //por que no da aqui error de instruccion?
    int b = 3;
    int c = 9;
    return; 
}


// switch (en el if si va)
